### ISSUE TITLE
todo

### ISSUE THREAD

**Issue by tingwei628** [tingwei628/Cpp_study#3]
## Basic Setup

- [x] Setup CMake
- [x] Setup Catch2
- [x] Build different types of libraries including **Static** , **Shared** , **Module(.dll)**

## Integraed with VSCode

- [ ] Test on VSCode
- [ ] Build with CMake on VSCode (tasks.json)
- [x] Debugging with LLDB on VSCode (launch.json)

## THIS IS OPTIONAL 

- [ ] HackerRank C++ Part
- [ ] Go through LearnCpp
- [ ] Ray Tracing implementation
- [ ] Game (youtube)
- [ ] JS binding Cpp (virtual-dom) + Test + Benchmark
- [ ] Review Algo && [DS](https://github.com/xtaci/algorithms) via Courses

## Clang++

- [ ] Build a shared lib
- [ ] Build a dynamic lib
- [ ] Build a static lib
- [ ] Link together 

## C++11

[C++ 11 FAQ by stroustrup](http://www.stroustrup.com/C++11FAQ.html)

[C++ 11 by EdisonX](https://www.ptt.cc/bbs/C_and_CPP/M.1359661212.A.4B7.html)

## HOW TO WRITE A C++ LIBRARY

REF: [cpp-TimSort@gfx](https://github.com/gfx/cpp-TimSort)

REF2: [hpp-skel@mapbox](https://github.com/mapbox/hpp-skel)

REF3: [CMakeLists in vault@pinebit](https://github.com/pinebit/vault/blob/master/src/CMakeLists.txt)

- [ ] Readme (installation, test, example, benchmark...)
- [ ] Build header files (.hpp) for use
- [ ] Create only .hpp with CMake
- [ ] Install with CMake (REF: [CMake - Install](https://zh.wikibooks.org/zh-tw/CMake_%E5%85%A5%E9%96%80/%E8%BC%B8%E5%87%BA%E4%BD%8D%E7%BD%AE%E8%88%87%E5%AE%89%E8%A3%9D))
- [ ] Benchmark
- [ ] Test
